@Library('test')_ 

def serverMap = parseInventory()
echo "Server Map: ${serverMap}"
// Example usage
// pipeline {
//     agent any

//     stages {
//         stage('Read Inventory') {
//             steps {
//                 script {
//                     def inventoryFilePath = '$WORKSPACE/Parse_Yaml/Devops/master_inventory.yaml' // Specify the correct path
//                     def serverMap = readInventoryYaml(inventoryFilePath)

//                     // Print the result
//                     echo "Server Map: ${serverMap}"
//                 }
//             }
//         }
//     }
// }